name: 💡 General Feature Request
description: Have a new idea/feature for the project? Please suggest!
title: "[FEATURE]"
labels: ["⭐ goal: addition"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the enhancement you propose, also include what you tried and what worked.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this idea?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](https://discord.gg/s9xNnaEY)
        Feel free to check out Curewell Homeo Clinic Organization [here](https://github.com/Curewell-Homeo-Clinic)
