# Generated by Django 3.2.9 on 2021-11-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admitted_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
