# Generated by Django 3.2.9 on 2021-11-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20211119_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
