# Generated by Django 3.2.9 on 2021-11-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='appointment',
        ),
    ]
