# Generated by Django 3.2.9 on 2021-11-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_invoice_pdf_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_link',
        ),
    ]
