# Generated by Django 3.2.9 on 2021-11-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_remove_invoice_pdf_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ailment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
